### ISSUE TITLE
[MASK] token attention patterns.

### ISSUE THREAD

**Issue by BogdanDidenko** [jessevig/bertviz#1]
Thanks for this repo and article. Also i think will be interesting visualize attention with special [MASK] token what used for BERT pre training. How it interacts with the other tokens in sequence.

**Comment by jessevig** [comment]
Good idea, thanks for the suggestion.

**Comment by jessevig** [comment]
Hi @BogdanDidenko thanks for your patience :) Support for this is now built into the Transformers library, so that if you have "<mask>" in your input sentence, the standard tokenizers will convert it to the mask token.
