### ISSUE TITLE
Problem with padding - RoBERTa for sequence classification

### ISSUE THREAD

**Issue by ClonedOne** [jessevig/bertviz#101]
Hello, I am trying to use this tool to visualize the attention heads of a RoBERTa for sequence classification model.

The inputs to the model are padded, and I am seeing this strange behavior where I get both errors:
```
ValueError: Attention has 512 positions, while number of tokens is 12 for tokens: 
```
if I pass only the non-padding tokens to `model_view` and
```
ValueError: Attention has 12 positions, while number of tokens is 512 for tokens: 
```
if I pass the full padded tokens.

Screenshot:
![image](https://user-images.githubusercontent.com/6853743/168855649-329070e9-527c-4c42-a738-b52b66d7f5c3.png)

As you can see in the screenshot the attention object I am passing is exactly the same.
![image](https://user-images.githubusercontent.com/6853743/168855723-d468a803-551b-49b8-acef-b44895464ed2.png)

Do you know what could be causing the issue?

Thanks

**Comment by jessevig** [comment]
Hi @ClonedOne, thanks for reporting. It looks like you are using a batch size of 16 here, though `model_view` is expecting a batch size of one. This then causes the `squeeze` function not to work properly and gives erroneous errors. In the next version, I will fix this so it gives a sensible error in the case when batch size is not 1. Let me know if you have any questions. Thanks!

**Comment by jessevig** [comment]
And this is probably obvious, as I think you were using the padded version for testing purposes, but the padded version probably won't render properly due to its size.

**Comment by ClonedOne** [comment]
Thank you @jessevig, I was confused by the seemingly contrasting error messages and didn't notice that.
