### ISSUE TITLE
Conda install

### ISSUE THREAD

**Issue by ChengkuiZhao** [jessevig/bertviz#102]
I cannot install it on my anaconda, the git install also doesn't work. Could you provide the way to install for anaconda like 'conda install bertviz' ? 
Thank you so much.

**Comment by jessevig** [comment]
Hi, @ChengkuiZhao does `pip install bertviz` work for you?

**Comment by ChengkuiZhao** [comment]
No, 'pip install bertviz' does not work for me, and when I used this command, it always showed the 'WARNING: ConnectTimeoutError' and 'ERROR: Could not find a version that satisfies the requirement bertviz' and 'ERROR: No matching ditribution found for bertviz'. Do you know where the problem is?

**Comment by ChengkuiZhao** [comment]
Thanks, it's the network problem, I used the proxy, and it always failed me. After I closed the proxy, I made it with the pip install bertviz.
