### ISSUE TITLE
bert visualization process

### ISSUE THREAD

**Issue by shoroukadel** [jessevig/bertviz#104]
I try to use the code in this link [https://github.com/cdpierse/transformers-interpret](https://github.com/jessevig/bertviz/issues/url) to a multi classification task for my pretrained model using bert function. To visualize bert work on my dataset of 6 different classes, trained my model and save it using model.save(). then when I try to load the model path to model I got this error.

`OSError: Can't load config for '/content/drive/Shared with me/Colab Notebooks/bert_visualization2.h5py'. Make sure that:

'/content/drive/Shared with me/Colab Notebooks/bert_visualization2.h5py' is a correct model identifier listed on 'https://huggingface.co/models'

or '/content/drive/Shared with me/Colab Notebooks/bert_visualization2.h5py' is the correct path to a directory containing a config.json file

**Comment by jessevig** [comment]
Hi @shoroukadel , it looks like you are pointing to a different repo (transformers-interpret). I'm going to close this issue for now, but feel free to reopen if I misunderstood the issue. Thanks.
