### ISSUE TITLE
it's not compatible with latest pytorch-transformers anymore

### ISSUE THREAD

**Issue by threefoldo** [jessevig/bertviz#11]
From the official document:`

>  The main breaking change when migrating from pytorch-pretrained-bert to pytorch-transformers is that the models forward method always outputs a tuple with various elements depending on the model and the configuration parameters.

It seems like the structure of attentions also changed. The attention for each layer is just a tensor, not key-value pairs.

**Comment by jessevig** [comment]
Hi, I have a special forked version of pytorch-transformers (pytorch-transformers-attn) within the repo that returns a different structure compared to the main pytorch-transformers repo. What error are you getting? Thanks.

**Comment by threefoldo** [comment]
Thanks for quick reply. The forked version is OK, I'm using it right now. The graph is great!

**Comment by jessevig** [comment]
Thank you!
