### ISSUE TITLE
How to summarize the attention scores?

### ISSUE THREAD

**Issue by celsofranssa** [jessevig/bertviz#111]
When forwarding sentence pair (`sentence A`, `sentence B`) through `BERT` (as shown below):

![0aaaa9662f9681a56e7d2216ee78636d0dc9400f](https://user-images.githubusercontent.com/11181748/200688854-a98fc458-b33a-42a1-a346-6699f93d2e06.jpeg)

Is there an approach to summarize the attention scores that each word of `sentence B` attends on each word of `sentence A`?

**Comment by jessevig** [comment]
Hi @celsofranssa sorry for the late response. To clarify, do you mean a model-level summarization of the attention scores across all heads and layers between a specific word in Sentence B and a specific word in Sentence A?

**Comment by iz2late** [comment]
same question here, any solutions to merge the attention scores across all heads and layers?
