### ISSUE TITLE
Image & Text attention

### ISSUE THREAD

**Issue by SuryaThiru** [jessevig/bertviz#112]
I'm looking to visualize the attention heads of models like [layoutlmv3](https://huggingface.co/docs/transformers/model_doc/layoutlmv3) that taken in both the text tokens and image inputs in a meaningful way. Is there a way I can do this with bertviz?

Thank you!

**Comment by jessevig** [comment]
Hi @SuryaThiru there may be a way to extend it somehow with the patch embeddings, but it isn't something I've looked at in detail. Sorry not to be more helpful here.
