### ISSUE TITLE
Cannot import bertviz

### ISSUE THREAD

**Issue by kumori123** [jessevig/bertviz#113]
Hi
I installed bertviz by "pip install bertviz" on my server, but I cannot import it. 
The error msg is 
```ImportError: cannot import name 'model_view' from partially initialized module 'bertviz' (most likely due to a circular import) ```
How could I solve it?
Thank you in advance!

**Comment by jessevig** [comment]
Hi @kumori123 are there any other directories / files named bertviz? Just looking at this issue: https://stackoverflow.com/a/66055075 . Not sure if this might happen if you do the pip install within the bertviz source.
