### ISSUE TITLE
Unable to load weights properly from tf checkpoint

### ISSUE THREAD

**Issue by aavshr** [jessevig/bertviz#14]
The  function ``` load_tf_weights_in_bert ``` in ``` modeling_bert.py ``` is buggy and throws a lot of attribute errors because of what seems as improper parsing of the variable names and the pointer pointing to the entire model.

For instance for the variable ```bert/encoder/layer_0/attention/output/dense/kernel ``` it throws an attribute error along the lines of ```Bert model has no attribute weight ``` because the pointer is the model ```bert``` itself whereas the pointer should be ```bert.encoder.layer.0.attention.output.dense```.

**Comment by jessevig** [comment]
Hi, thanks for reporting this. This function is part of the codebase from pytorch-transformers https://github.com/huggingface/pytorch-transformers. Could you check that you get the same errors when using their library directly? If so, you might consider an issue in that repo directly, as they will be in a better position to address it. Please share here if you do file an issue with them, so I can update this codebase as well. Thanks.

**Comment by jessevig** [comment]
By the way, I've recently pushed in a change that enables you to invoke the transformers library directly, rather than using a forked version. Please let me know if you're still having any issues.

**Comment by aavshr** [comment]
I patched a small workaround in my fork for my needs. Thank you. I'll close the issue here as I already submitted the issue in the [pytorch transformers](https://github.com/huggingface/transformers) repo but did not get any response.
