### ISSUE TITLE
Missing [CLS] token in XLNet 

### ISSUE THREAD

**Issue by PradyumnaGupta** [jessevig/bertviz#15]
I want to know why there is not CLS token in the visualizaition of XLNet . I used your XLNet code to visualize my fine tuned XLNet but I am not getting in any [CLS] token in the input . Can you tell , how can i get that ?

**Comment by jessevig** [comment]
Hi, thanks for filing this. I just put in a change that will add the [CLS] and [SEP] tokens in the case of a single input sentence. Please let me know if this works for you. Eventually will add support for the sentence-pair case as well.
