### ISSUE TITLE
Visualize large BERT model

### ISSUE THREAD

**Issue by jxiaoF8** [jessevig/bertviz#2]
Thank you for the great work! Is it possible to make this work with the large uncased BERT model as well? Currently it loads the model but the Layer dropdown is not populated and the visualization is not shown. Simply changing the hardcoded layers from 12 to 24 in attention.js does not work.

**Comment by jessevig** [comment]
Thanks for the suggestion. I hope to add this feature at some point.

**Comment by jessevig** [comment]
Okay, BERT large should work now. Thanks again for pointing this out!
