### ISSUE TITLE
Hovering issue

### ISSUE THREAD

**Issue by Kesin1** [jessevig/bertviz#20]
Hello, thanks for the work. 
Short bug report.
In safari, when you are hovering over the visualisation in google colab, the window in of the visualisation is scrolling down automatically, making it impossible to work with model_view and neuron_view. Works in chrome.

Thanks again

**Comment by jessevig** [comment]
Thanks for reporting that. Unfortunately I'm not able to replicate it exactly. However, I'm having a different issue in Safari where the visualization only loads if you refresh the page.

**Comment by WesselBosscher** [comment]
Hi there,
I also encounter the same hovering issue for both safari and chrome. the model view seems to work fine for me.
Thanks!

[Screen Recording 2019-11-27 at 21.20.53.zip](https://github.com/jessevig/bertviz/files/3898666/Screen.Recording.2019-11-27.at.21.20.53.zip)

**Comment by jessevig** [comment]
Hi,
Thanks for reporting this. Unfortunately I'm still not able to reproduce it. I've pushed some changes to the notebooks in the last few days. I don't think they address this problem you are experiencing, but one suggestion would be to check out the latest version. I'm also curious if the notebook works for you prior to running it. The visualization should be there when you open the notebook even prior to running. Please let me know if you get a chance.
