### ISSUE TITLE
word attention weights

### ISSUE THREAD

**Issue by vr25** [jessevig/bertviz#23]
Hi,

Thank you for writing this tool.

I was wondering if there is any way to compute word-level attention and also point their respective positions within the context of a sentence in a given multi-sentence text.

Sticking to the same example below, how to find the BERT word attention for "cat" in two different sentences:
[the cat sat on the mat. the cat lay on the rug.]

Thanks!

**Comment by jessevig** [comment]
Thanks! Sorry, not quite following what you are asking above. Can you explain how the tool is not supporting this, so I can better understand?

**Comment by vr25** [comment]
Thank you for your reply. 

I see, sorry, I will try to further explain my issue. I am actually trying to find if there is any way I can "print out" the attention scores for each word at each layer.

Thanks!

**Comment by jessevig** [comment]
Hi, you can access the attention weights by setting output_attention = True in your call to any model from transformers:
`attention = model(input_ids, token_type_ids=token_type_ids)[-1]`
See https://github.com/jessevig/bertviz/blob/master/head_view_bert.ipynb for the context.

**Comment by vr25** [comment]
Thanks for you reply.

I am actually trying to find the attention scores, please find the details [here](https://github.com/huggingface/transformers/issues/2054).
