### ISSUE TITLE
Multiple visualization for multiple sentences at one display

### ISSUE THREAD

**Issue by zahrakolagar** [jessevig/bertviz#24]
Hi,
Thanks for your great tool.
I was wondering if it is possible to display multiple visualization for multiple sentences at once in one display? If yes, I would be grateful if you guide me on how to do it.
Thank you very much in advance

**Comment by jessevig** [comment]
Hi,
Unfortunately it is not possible in the current tool, but this is a good suggestion. Thanks.

**Comment by jessevig** [comment]
The tool now supports having multiple instances of the head view and model view visualization in a single notebook (and so each could be for a separate sentence). Not sure this is exactly what you're asking for though.
