### ISSUE TITLE
How can use bertviz for Bert Questioning Answering??

### ISSUE THREAD

**Issue by bvy007** [jessevig/bertviz#26]
Is there any way to see the attention visualization for Bert Questioning and Answering model ?? Because I couldn't see BertForQuestionAnswering class in bertviz.pytorch_transformers_attn? I have fine-tuned over a QA dataset using hugging-face transformers and wanted to see the visualization for it. Can you suggest any way of doing it ??

**Comment by jessevig** [comment]
Hi, I've recently pushed some significant changes that enable you to run any model from the transformers library. If you are using the head view, you should be able to adapt the following notebook for your use case: https://github.com/jessevig/bertviz/blob/master/head_view_bert.ipynb
Please let me know if that works for you.

**Comment by bvy007** [comment]
Thanks for the quick reply. I tried out but it didn't show anything. I did as following:

```
from bertviz import head_view
from transformers import BertTokenizer, BertForQuestionAnswering

%%javascript
require.config({
  paths: {
      d3: '//cdnjs.cloudflare.com/ajax/libs/d3/3.4.8/d3.min',
      jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min',
  }
});

def show_head_view(model, tokenizer, sentence_a, sentence_b=None):
    inputs = tokenizer.encode_plus(sentence_a, sentence_b, return_tensors='pt', add_special_tokens=True)
    token_type_ids = inputs['token_type_ids']
    input_ids = inputs['input_ids']
    attention = model(input_ids, token_type_ids=token_type_ids)[-1]
    input_id_list = input_ids[0].tolist() # Batch index 0
    tokens = tokenizer.convert_ids_to_tokens(input_id_list)
    if sentence_b:
        sentence_b_start = token_type_ids[0].tolist().index(1)
    else:
        sentence_b_start = None
    head_view(attention, tokens, sentence_b_start)


do_lower_case = True
model = BertForQuestionAnswering.from_pretrained('bert_output/', output_attentions=True)
tokenizer = BertTokenizer.from_pretrained('bert_output/', do_lower_case=do_lower_case)
sentence_a = "The cat sat on the mat"
sentence_b = "The cat lay on the rug"
show_head_view(model, tokenizer, sentence_a, sentence_b)
```

Here 'bert_output/' is a directory that has the model('pytorch_model.bin') in it which I finetuned over a specific dataset.
Could you please correct me if I am wrong?

**Comment by jessevig** [comment]
Hmm, I suspect the model is not getting loaded correctly. I believe the directory might need a configuration file as well, though I can't recall. Are you able to display the value of attention that is being returned when you call your model?

**Comment by bvy007** [comment]
I can see values when printing the `attention `variable in `show_head_view()`

![image](https://user-images.githubusercontent.com/6167208/69890888-c71d5880-12f8-11ea-8629-626efaa423be.png)

**Comment by jessevig** [comment]
Okay, I think I see the problem in the second version. You need to set output_attentions=True. Want to try again with that change and let me know if it works?

**Comment by bvy007** [comment]
I tried as following:
```
import torch
model_version = 'bert-base-uncased'
do_lower_case = True
model_state_dict = torch.load('bert_output/pytorch_model.bin')
model = BertForQuestionAnswering.from_pretrained(model_version, state_dict=model_state_dict, output_attentions=True)
tokenizer = BertTokenizer.from_pretrained('bert_output/', do_lower_case=do_lower_case)
sentence_a = "The cat sat on the mat"
sentence_b = "The cat lay on the rug"
show_head_view(model, tokenizer, sentence_a, sentence_b)
```

But ended up showing nothing in the view as below in the figure

![image](https://user-images.githubusercontent.com/6167208/69891200-0351b880-12fb-11ea-9949-fb6d1a1c60f0.png)

**Comment by jessevig** [comment]
Are you able to display the value of the attention returned again?

**Comment by bvy007** [comment]
Yes I could see all the attention values without any error this time. 

![image](https://user-images.githubusercontent.com/6167208/69891298-dd78e380-12fb-11ea-9a93-ff8d126b282d.png)

**Comment by bvy007** [comment]
Do i need to check with website settings(d3) for the visualization???

**Comment by jessevig** [comment]
The attention looks good.

It might relate to the website settings. Do you still have the following at the top?:

%%javascript
require.config({
  paths: {
      d3: '//cdnjs.cloudflare.com/ajax/libs/d3/3.4.8/d3.min',
      jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min',
  }
});

I'm working on a change where this is not needed, but currently it is. Sometimes there's some weirdness where you have to refresh your browser. Which browser are you using by the way?

**Comment by bvy007** [comment]
The javascript code looks good.

Yeah I was thinking the same. Maybe I have some problem with the browser. I am currently using google chrome.

**Comment by jessevig** [comment]
Hmm, not sure if problem is with browser or not. Are you able to run the original version of the notebook without using your pretrained model?

**Comment by bvy007** [comment]
I guess there is a problem with the browser. The fine-tuned model is also giving me the similar results. 

![image](https://user-images.githubusercontent.com/6167208/69891702-ca1b4780-12fe-11ea-99c6-eaa6d559c2ea.png)

**Comment by jessevig** [comment]
Occassionally it doesn't work the first time. Could you try re-running from the beginning. If that doesn't work could you close and re-open your browser? If that doesn't work, could you check the Javascript console for any errors?

**Comment by bvy007** [comment]
Sure Thank you so much ! :)

**Comment by bvy007** [comment]
Hi found this error in the web browser:

```
output_binary.js?vrz=colab-20191126-082400-RC00_282570569:75 Error evaluating Javascript output:  ReferenceError: requirejs is not defined
    at eval (eval at <anonymous> (output_binary.js?vrz=colab-20191126-082400-RC00_282570569:NaN), <anonymous>:12:1)
    at eval (<anonymous>)
    at ta.eval [as c] (output_binary.js?vrz=colab-20191126-082400-RC00_282570569:75)
    at va (output_binary.js?vrz=colab-20191126-082400-RC00_282570569:14)
    at xa.next (output_binary.js?vrz=colab-20191126-082400-RC00_282570569:14)
    at eval (output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15)
    at new Promise (<anonymous>)
    at ya (output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15)
    at y (output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15)
    at td (output_binary.js?vrz=colab-20191126-082400-RC00_282570569:74)
eval @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:75
va @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:14
next @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:14
eval @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
ya @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
y @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
td @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:74
eval @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:74
va @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:14
next @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:14
eval @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
ya @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
y @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
pd @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:73
eval @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:70
va @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:14
next @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:14
eval @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
ya @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
y @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
T.g @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:70
X.g @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:113
U.F @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:96
qe.F @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:120
eval @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:95
va @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:14
next @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:14
b @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
Promise.then (async)
f @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
eval @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
ya @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
y @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
Sd @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:94
eval @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:94
va @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:14
next @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:14
eval @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
ya @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
y @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:15
Pd @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:94
U.u.onmessage @ output_binary.js?vrz=colab-20191126-082400-RC00_282570569:91
```

**Comment by jessevig** [comment]
I see, thanks. So you're running on Colab? Sorry, I was assuming you were running it on your local machine with Jupyter notebook. Colab requires a different javascript setup, as shown here: https://colab.research.google.com/drive/1PEHWRHrvxQvYr9NFRC-E_fr3xDq1htCj#scrollTo=Mv6H9QK9yLLe

Instead of:

%%javascript
require.config({
paths: {
d3: '//cdnjs.cloudflare.com/ajax/libs/d3/3.4.8/d3.min',
jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min',
}
})

You need:

def call_html():
  import IPython
  display(IPython.core.display.HTML('''
        <script src="/static/components/requirejs/require.js"></script>
        <script>
          requirejs.config({
            paths: {
              base: '/static/base',
              "d3": "https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.8/d3.min",
              jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min',
            },
          });
        </script>
        '''))

And then you need to add this line right before you invoke head_view(): call_html()

Please let me know if that works. Sorry, working on making this more uniform between platforms. Javascript is always a challenge, especially in Colab!

**Comment by bvy007** [comment]
Yeah. It works now Thank you so much !!
:)

**Comment by jessevig** [comment]
Awesome, glad to hear. Working on changes to make this easier in the future. Thanks.

**Comment by bvy007** [comment]
One more question, Sometimes I see in colab note book that I see "Runtime Disconnected" error when using long sequences. Is that common??

**Comment by jessevig** [comment]
I hadn't seen that before, but I'm not surprised that it might happen for very long sequences. How long are the sequences?

**Comment by jessevig** [comment]
Also do you know if that error happens after the attentions have been returned, or before? I'm assuming it probably happens between code where attention is computed and visualization is rendered, but curious.

**Comment by bvy007** [comment]
length of sequence sentence_a = 40
length of sequence sentence_b = 225

Yes It happens in between attention calculation and rendering

**Comment by bvy007** [comment]
sentence_a = "who plays lady talisa in game of thrones"
sentence_b = "<P> Oona Castilla Chaplin ( ˈuna kasˈtija ˈt͡ʃaplin ) ( born 4 June 1986 ) , known professionally as Oona Chaplin , is a Spanish actress . Her roles include Talisa Maegyr in the HBO TV series Game of Thrones , The Crimson Field and the series Taboo . </P>"

**Comment by jessevig** [comment]
Thanks for sharing that. The tool doesn't currently scale well to long texts unfortunately.
