### ISSUE TITLE
Runtime disconnected frequently

### ISSUE THREAD

**Issue by chikubee** [jessevig/bertviz#28]
I am using bertviz with BertModel for visualisation., I'm using the neuron detail viz. Every time I pass a sentence of more than 5 words., the runtime gets disconnected. Is their someway else to still visualise them, I am trying to understand long term dependencies.

**Comment by jessevig** [comment]
Hmm, I haven't run into this before. What sort of system are you running this on? I've mainly tested on Macbook Pro on Chrome.  Are you able to try this Colab notebook?: https://colab.research.google.com/drive/1m37iotFeubMrp9qIf9yscXEL1zhxTN2b#scrollTo=d7lGFcIRQj7H

**Comment by dndimitri** [comment]
Hi! I have the same problem with BertViz using the neuron_view and sometimes with head_view. Is there any possible solution? I test it on Colab.

**Comment by jessevig** [comment]
I'm having this issue with Colab as well, but I'm able to run the longer inputs on a local Jupyter notebook without a problem (running on Macbook Pro). Are you able to try this on a Jupyter notebook locally?
