### ISSUE TITLE
How to use model i've trained in this project

### ISSUE THREAD

**Issue by TLCFYBJJHYYSND** [jessevig/bertviz#29]
i've use the bert from huggingface to fine tuning the model for my task already. And i'm trying to use my model in this project so i can see my model in these 3 style provided in this project.
By the way, my task is text classification with pair of sentence.
Finally,thanks a lot to this paper and project, it's so excellent

**Comment by jessevig** [comment]
For the model view and head view, you should be able to load your model the same way you normally would, but pass "outputAttentions" = True when you call the model. Then the rest should be like the sample notebook, e.g.  https://github.com/jessevig/bertviz/blob/master/head_view_bert.ipynb . Do you have the latest version of BertViz? Let me know if that works for you.
