### ISSUE TITLE
encode_plus is not in GPT2 Tokenizer

### ISSUE THREAD

**Issue by mojivalipour** [jessevig/bertviz#31]
It seems you removed encode_plus, what is the successor? All the notebook includes `inputs = tokenizer.encode_plus(text, return_tensors='pt', add_special_tokens=True)` which is wrong and raise an error.

**Comment by jessevig** [comment]
Hi,  GPT2Tokenizer should come from the Transformers library (pip install transformers), which is external to BertViz. Do you know which version of transformers you are using?

**Comment by mojivalipour** [comment]
seeing "from bertviz.bertviz.transformers_neuron_view import GPT2Model, GPT2Tokenizer" I thought you'd implemented something specific different than Transformer's original version. 

The GPT2Tokenizer from bertviz.transformers_neuron_view has not implemented encode_plus ("AttributeError: 'GPT2Tokenizer' object has no attribute 'encode_plus'") and the transformer's version don't support neuron_view show function because of this error:
`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-5681f9e6ea51> in <module>
----> 1 show(model=model, model_type='gpt2', tokenizer=tokenizer, sentence_a=text)

/data/m5valipo/m5/transformers/bertviz/bertviz/neuron_view.py in show(model, model_type, tokenizer, sentence_a, sentence_b)
     58         os.path.join(os.getcwd(), os.path.dirname(__file__)))
     59     vis_js = open(os.path.join(__location__, 'neuron_view.js')).read()
---> 60     attn_data = get_attention(model, model_type, tokenizer, sentence_a, sentence_b, include_queries_and_keys=True)
     61     if model_type == 'gpt2':
     62         bidirectional = False

/data/m5valipo/m5/transformers/bertviz/bertviz/neuron_view.py in get_attention(model, model_type, tokenizer, sentence_a, sentence_b, include_queries_and_keys)
    157     for layer, attn_data in enumerate(attn_data_list):
    158         # Process attention
--> 159         attn = attn_data['attn'][0]  # assume batch_size=1; shape = [num_heads, source_seq_len, target_seq_len]
    160         attn_dict['all'].append(attn.tolist())
    161         if is_sentence_pair:

TypeError: new(): invalid data type 'str'
`

However, 2.3.0 is the version that I am currently using. There is a disintegration between these two libraries. Any idea of how I can use only one of these tokenizers?

**Comment by mojivalipour** [comment]
OK, it seems the second problem is because of a change in the transformer library. You can check [here](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_gpt2.py#L199). They don't use a dictionary anymore, and therefore they don't return queries and keys too.

**Comment by mojivalipour** [comment]
One dirty solution is using your model and the transformer's tokenizer. 

```
from bertviz.bertviz.transformers_neuron_view import GPT2Model
from transformers import GPT2Tokenizer
from bertviz.bertviz import model_view, neuron_view, head_view
from bertviz.bertviz.neuron_view import show
```

**Comment by jessevig** [comment]
Thanks for the additional information. Which view are you using? The neuron view is invoked differently from the other views.

See https://github.com/jessevig/bertviz/blob/master/neuron_view_gpt2.ipynb for how to invoke the neuron view. Here GPT2Tokenizer is imported from bertviz.transformers_neuron_view. However, encode_plus is not invoked.

See https://github.com/jessevig/bertviz/blob/master/head_view_gpt2.ipynb for how to invoke the head (and model view). In this case, GPT2Tokenizer is imported from the external huggingface transformers library. Calling encode_plus should work in this case.

Please let me know if this resolves your issue.  On my end I'll make the differences in the APIs of the different views more explicit in the README beyond just having the separate notebooks. By the way, the reason the neuron view is handled differently is that it requires access to the query and key vectors (not just attention weights), which aren't made available by the external transformers library. The other two views just need the attention weights.

**Comment by mojivalipour** [comment]
Yes, but I was looking for a solution that helps me to load only one model and, at the same time, works for all views in one jupyter notebook which I've already found out you've adopted different javascript for each view.

**Comment by liygzting** [comment]
> seeing `"from bertviz.bertviz.transformers_neuron_view import GPT2Model, GPT2Tokenizer"` I thought you'd implemented something specific different than Transformer's original version.
> 
> The `GPT2Tokenizer `from `bertviz.transformers_neuron_view` has not implemented encode_plus (`"AttributeError: 'GPT2Tokenizer' object has no attribute 'encode_plus'"`) and the transformer's version don't support neuron_view show function because of this error:
> 
> ```
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-21-5681f9e6ea51> in <module>
> ----> 1 show(model=model, model_type='gpt2', tokenizer=tokenizer, sentence_a=text)
> 
> /data/m5valipo/m5/transformers/bertviz/bertviz/neuron_view.py in show(model, model_type, tokenizer, sentence_a, sentence_b)
>      58         os.path.join(os.getcwd(), os.path.dirname(__file__)))
>      59     vis_js = open(os.path.join(__location__, 'neuron_view.js')).read()
> ---> 60     attn_data = get_attention(model, model_type, tokenizer, sentence_a, sentence_b, include_queries_and_keys=True)
>      61     if model_type == 'gpt2':
>      62         bidirectional = False
> 
> /data/m5valipo/m5/transformers/bertviz/bertviz/neuron_view.py in get_attention(model, model_type, tokenizer, sentence_a, sentence_b, include_queries_and_keys)
>     157     for layer, attn_data in enumerate(attn_data_list):
>     158         # Process attention
> --> 159         attn = attn_data['attn'][0]  # assume batch_size=1; shape = [num_heads, source_seq_len, target_seq_len]
>     160         attn_dict['all'].append(attn.tolist())
>     161         if is_sentence_pair:
> 
> TypeError: new(): invalid data type 'str'
> ```
> 
> However, 2.3.0 is the version that I am currently using. There is a disintegration between these two libraries. This problem is most probably because of Python 3.5.7 or some inheritance issue. Any idea of how I can use only one of these tokenizers?

the same issue when I run neuron view in colab.
![截屏2020-12-21 21 28 35](https://user-images.githubusercontent.com/73510109/102781993-8a287600-43d3-11eb-8a3c-4b0b0ab71e81.png)

**Comment by jessevig** [comment]
Hi, could you share the previous steps in the notebook to assist with debugging?

**Comment by liygzting** [comment]
All right
the code in my local env
```
import numpy as np
import torch
from transformers import GPT2LMHeadModel, BertTokenizer
from bertviz.neuron_view import show
def call_html():
  import IPython
  display(IPython.core.display.HTML('''
        <script src="/static/components/requirejs/require.js"></script>
        <script>
          requirejs.config({
            paths: {
              base: '/static/base',
              "d3": "https://cdnjs.cloudflare.com/ajax/libs/d3/5.7.0/d3.min",
              jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min',
            },
          });
        </script>
      '''))

vocab_file = "./dtc_vocab.txt"
tokenizer = BertTokenizer(vocab_file=vocab_file)
model_path = "./model_epoch11"
# model = GPT2Model.from_pretrained(model_path, output_attentions=True)
model = GPT2LMHeadModel.from_pretrained(model_path)

model_type = "gpt2"
text = "C19887 918F96 91C300 C16487 C21487 C19887 C43381 C43381 C19887 C19887 C19887 C11287 534104 C19887 918F96 91C300 C16487 C21487 C19887 C43381"
show(model, model_type, tokenizer, text)
```

and error looks like that
![Error](https://user-images.githubusercontent.com/73510109/102896525-7cd9bd00-44a1-11eb-9c68-f23aa4fb2fa9.png)

**Comment by jessevig** [comment]
For the neuron view, you have to use the version of the Huggingface models that are defined within BertViz, e.g.:

from bertviz.transformers_neuron_view import GPT2Model, GPT2Tokenizer

The reason is that they have custom code to return the query and key values needed in the neuron view. Let me know if that works for you. I'll make this more clear in the README.

**Comment by liygzting** [comment]
Thank you @jessevig 
When i changed to bertviz.transformers_neuron_view，the error did not appear
![result](https://user-images.githubusercontent.com/73510109/102995292-b53dd180-455b-11eb-8cc7-c91007d3f453.png)
But the result I wanted did not appear

Thanks

**Comment by jessevig** [comment]
Hi, could you try changing the javascript import to what is shown here?:

https://github.com/jessevig/bertviz/blob/master/neuron_view_gpt2.ipynb

**Comment by jessevig** [comment]
That is if running in a local env

**Comment by liygzting** [comment]
yes I run in my local env,
both javascript config and call_html()
still nothing appeared
![截屏2020-12-24 00 05 51](https://user-images.githubusercontent.com/73510109/103016103-81bf6f00-457c-11eb-9d95-d27801bac07b.png)
Thanks

**Comment by jessevig** [comment]
Hmm, I'm not sure then. I was able to successfully run the notebook https://github.com/jessevig/bertviz/blob/master/neuron_view_gpt2.ipynb, and I'm not sure what's different about your code that would cause this issue. 

Are you able to run that notebook?

**Comment by liygzting** [comment]
the demo is ok
thanks

**Comment by jessevig** [comment]
I see. And the imports in your version are exactly the same as in the demo notebook? In that case I would recommend adding some debug statements to neuron_view,py, to see what is being returned from the model, e.g. the final line here:

![image](https://user-images.githubusercontent.com/45317205/103152257-31424000-473b-11eb-958b-19adc3e495b1.png)

**Comment by liygzting** [comment]
The latest repo is ok to re-run
![IMG_20201229_202856.jpg](https://user-images.githubusercontent.com/73510109/103283875-af8d3380-4a14-11eb-8c0b-19154531b19c.jpg)

Thanks 👍
