### ISSUE TITLE
Interpretability of a BERT model's intermediate layers

### ISSUE THREAD

**Issue by jclevesque** [jessevig/bertviz#34]
Hi,

I have a general question. If you feel like this is not relevant / don't feel like discussing this here, feel free to close this issue. Why do you associate the values of intermediate layers of the transformer with the input tokens? Is there a property of BERT/transformers that binds the representation to those specific tokens?

The way I see it, the representation of layer i + 1 is essentially a weighted sum over the input sequence. If attention chooses to give zero weight to the input token/hidden vector, the new representation will be absolutely unrelated to the initial input sequence. So what does it tell us that layer 5 is paying attention to the hidden representation of elements 4-5 in layer 4? Are they really still associated with the initial input tokens? Do you see what I'm getting at?

**Comment by jessevig** [comment]
This is a good point, and there is a recent paper that makes this same point though I can't recall its name. I think of the word labels as shorthand for "the position of this word", but I agree that this shorthand can also be misleading. Different models produce output representations of different similarity levels to input embeddings.
