### ISSUE TITLE
How to use saved model for bertviz

### ISSUE THREAD

**Issue by nargesam** [jessevig/bertviz#35]
Hi, 

I am using huggingface's transformers BertForSequenceClassification to train a BERT model. Now, I want to load my saved model and use it in your head_view_bert  notebook. It does not assume a local model... Can you tell me how to fix this? here's my code: 

model_version = 'bert-base-cased'
do_lower_case = True
modelpath = '~/Documents/insight/projects/factCC/models/saved_models/'
model = BertForSequenceClassification.from_pretrained(modelpath, from_tf=True)

# model = BertModel.from_pretrained(model_version, output_attentions=True)
tokenizer = TFBertTokenizer.from_pretrained(model_version, do_lower_case=do_lower_case)
sentence_a = "The cat sat on the mat"
sentence_b = "The cat lay on the rug"
show_head_view(model, tokenizer, sentence_a, sentence_b)

This is the was I load my model normally for test data and prediction... yet I can't load it here... here's the error I get: 

OSError                                   Traceback (most recent call last)
<ipython-input-10-4771a8f4bfbf> in <module>
      2 do_lower_case = True
      3 modelpath = '~/Documents/insight/projects/factCC/models/saved_models/'
----> 4 model = BertForSequenceClassification.from_pretrained(modelpath, from_tf=True)
      5 
      6 # model = BertModel.from_pretrained(model_version, output_attentions=True)

/usr/local/lib/python3.6/site-packages/transformers/modeling_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    348                 resume_download=resume_download,
    349                 proxies=proxies,
--> 350                 **kwargs
    351             )
    352         else:

/usr/local/lib/python3.6/site-packages/transformers/configuration_utils.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    171                         ', '.join(cls.pretrained_config_archive_map.keys()),
    172                         config_file, CONFIG_NAME)
--> 173             raise EnvironmentError(msg)
    174 
    175         except json.JSONDecodeError:

OSError: Model name '~/Documents/insight/projects/factCC/models/saved_models/' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, bert-base-japanese, bert-base-japanese-whole-word-masking, bert-base-japanese-char, bert-base-japanese-char-whole-word-masking, bert-base-finnish-cased-v1, bert-base-finnish-uncased-v1). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/~/Documents/insight/projects/factCC/models/saved_models//config.json' was a path or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

**Comment by jessevig** [comment]
Hi, so you are getting an error when you run the following statement, but only when you run it in the context of BertViz?:

`model = BertForSequenceClassification.from_pretrained(modelpath, from_tf=True)`

How are you importing BertForSequenceClassification?

**Comment by shishishu** [comment]
@nargesam 

Hello, I think the modelpath you passed here some like remote model and it seems need to be downloaded but fail to find it.  You can ref as following if want to load local model:

```
config = BertConfig.from_json_file('local_model_dir/bert_config.json')
config.output_attentions = True
model = BertModel.from_pretrained('local_model_dir/model.ckpt-656.index', from_tf=True, config=config)
```

I think in modelpaht, file name ends with 'index' is necessary. Let me know if any questions.
