### ISSUE TITLE
How to change the model_version to my own Fine-Tune BERT model 

### ISSUE THREAD

**Issue by WenTingTseng** [jessevig/bertviz#38]
Hello, I want to ask about how to change the model_version to my own Fine-Tune BERT model in the head_view_bert.ipynb case
When I try to change to my model like this it always has the error
![擷取](https://user-images.githubusercontent.com/32416416/74160643-b07c7180-4c58-11ea-894d-5154a1a9c656.JPG)

**Comment by jessevig** [comment]
Hi, does this help?: https://github.com/huggingface/transformers/issues/138#issuecomment-451916287 . At the bottom of that comment, he also points to a few more examples.

**Comment by WenTingTseng** [comment]
Thanks a lot
When I change another jupyter notebook(open new one file) and it works
