### ISSUE TITLE
Chinese BERT model can be used represented by words instead of character

### ISSUE THREAD

**Issue by WenTingTseng** [jessevig/bertviz#40]
I want to ask about the Chinese BERT model can be used represented by words instead of character?
Because when I do BERT visual for Chinese can only see its attention from character to character.
I want to see attention from words to words. Can I change this?

Thanks a lot for your help

**Comment by shishishu** [comment]
You can try to use pre-trained model of [Chinese version](https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip) and set tokenizer:
```
tokenizer = BertTokenizer.from_pretrained('spec_dir/chinese_L-12_H-768_A-12/vocab.txt', do_lower_case=True)
```
Let me know if any questions.

<img width="356" alt="WeChat Image_20200313211127" src="https://user-images.githubusercontent.com/20367654/76623876-3ac53780-656f-11ea-9189-cfda9a308472.png">
