### ISSUE TITLE
Save attention visualizations as local html file

### ISSUE THREAD

**Issue by Nikoschenk** [jessevig/bertviz#41]
I'm running the attention visualizations on a server without GUI.
Is there an easy way to run, e.g., `head_view_bert.py `and save the interactive visualizations to a local .html file which can then be viewed on another machine?

**Comment by jessevig** [comment]
Hi, I think it's probably possible, though I haven't tried it. There is a variable vis_html that could be written to a file I believe: https://github.com/jessevig/bertviz/blob/2695d30474777a5bfe36219f1d66ed1030c1a3e1/bertviz/head_view.py#L40 . Note that there is some javascript in the notebooks that would have to be included as well likely: https://github.com/jessevig/bertviz/blob/master/head_view_bert.ipynb

**Comment by Paul-Trax** [comment]
Any idea how to apply     
display(Javascript('window.params = %s' % json.dumps(params)))
display(Javascript(vis_js))

to saved html file ?

**Comment by Sardhendu** [comment]
I am struggling with it. Any chance, you guys have figured out how to save it as a HTML?

**Comment by cyber-raskolnikov** [comment]
Hi,
I have implemented the feature that actually allows you to return the HTML visualizations.
You can use it by checking the fork I'm actually trying to pull request right now, it is also available at my forked repo.

Hope it'll be of help, further instructions on how to retrieve them are documented at the updated README.

**Comment by jessevig** [comment]
Thanks to @cyber-raskolnikov this is now available in version 1.4.0. See https://github.com/jessevig/bertviz#obtain-html-representations
