### ISSUE TITLE
Unable to visualize more than once in the same notebook

### ISSUE THREAD

**Issue by venkatasg** [jessevig/bertviz#45]
Thank you for your work on this repo - the visualizations are really useful and helpful towards my research. I'm wondering if I've run into some sort of bug or limitation of the visualizations, because I'm unable to show more than one visualization in a notebook - in two different cells that is. The second cell always shows an empty output when I try to run it (See attached picture). I see the same behavior with all the views.

<img width="972" alt="Screen Shot 2020-04-24 at 4 26 06 PM" src="https://user-images.githubusercontent.com/22871413/80258259-66e0d780-8648-11ea-9d14-e4c2f9c778af.png">

_Update_: I've also noticed that sometimes the second visualization is displayed, but then the first visualization disappears.

**Comment by jessevig** [comment]
Hi, sorry for the late reply. Running the visualization in multiple cells isn't a use-case that I had tested. Unfortunately I don't have the cycles to investigate this further right now, but I'm flagging this as a bug to look into later. I'm open to suggestions/PRs  if anyone else has insights on this.  That being said, I've noticed that Chrome generally is more stable than other browsers. Can you tell me which browser you're using? Also, I assume you are running the notebook locally as opposed to in Colab?

**Comment by venkatasg** [comment]
I'm using the latest version of Safari. I'll try the same with Chrome and report what I find. And yes, I'm running this locally.

**Comment by jessevig** [comment]
Hi, yes there is an issue with combining some of the different visualizations in the same notebook, due to conflicting javascript imports. I will work on that one but can't give a timeline at the moment unfortunately.

**Comment by jessevig** [comment]
This has been resolved in latest version.
