### ISSUE TITLE
General Question about word embedding and gradient output

### ISSUE THREAD

**Issue by JiayuanDing100** [jessevig/bertviz#46]
Hi,
I am using  BertForSequenceClassification to do binary classification task. Do you know how to get  word embedding and gradient output for each word in BertForSequenceClassification https://github.com/huggingface/transformers/blob/7d7fe4997f83d6d858849a659302b9fdc32c3337/src/transformers/modeling_bert.py#L1075?

My use case: I want model to automatically tag a certain number of indicative words in test sentence to interpret why this sentence is labeled as COVID or non COVID. So my solution is to interpret this using gradient. But i haven't figured out how to output word embedding and gradient

**Comment by DavideStenner** [comment]
@JiayuanDing100 try look at this 
https://colab.research.google.com/drive/1tTiOgJ7xvy3sjfiFC9OozbjAX1ho8WN9?usp=sharing
