### ISSUE TITLE
model_view shows black image?

### ISSUE THREAD

**Issue by Shikib** [jessevig/bertviz#49]
Hi there,

First of all, thank you for building this package. It's exactly what I'm looking for right now! :)

I'm trying to use `model_view` to visualize the attention. I can use `head_view` and it works perfectly fine, but when I try to use `model_view` with everything else the same -- I just get a black rectangle. See the image below.

![image](https://user-images.githubusercontent.com/7698375/86300037-8d763e00-bbb6-11ea-95e0-0b700814f7f4.png)

Any suggestions would be much appreciated.

**Comment by jessevig** [comment]
Hi, the javascript imports are slightly different between the model view and the head view. I plan to make some changes soon to simplify the process of having multiple views in a given notebook.

**Comment by jessevig** [comment]
This has been resolved with latest changes.
