### ISSUE TITLE
Attention matrix is asymmetric

### ISSUE THREAD

**Issue by sronnqvist** [jessevig/bertviz#5]
Hi Jesse,
I find you work very interesting, thanks a lot for putting it out there!

I was digging into the attention values being visualized in the BERT map, specifically the return value of `_get_attentions()`, and found that the token-to-token attention weights are not symmetrical, as I would have expected. For instance, consider:
```
layer, head = 11, 0
att = _get_attentions(tokens_a, tokens_b, atts)
attmx = np.array(att['a']['att'][layer][head])
```
Here, the matrix `attmx` might look like this:
```
array([[0.10391058, 0.09832697, 0.09166335, 0.14575878, 0.08784127],
       [0.09632228, 0.09650009, 0.09524056, 0.12355924, 0.09061429],
       [0.12465193, 0.10896012, 0.11306546, 0.11939598, 0.10786319],
       [0.09877665, 0.10982872, 0.08591022, 0.11621149, 0.1339225 ],
       [0.11143579, 0.0954979 , 0.09444219, 0.1312461 , 0.07381313]])
```
How should the fact that it's asymmetrical be interpreted? If we consider the [CLS] token at the output layer (layer 11 in bert-base?), would the attention it receives from the second token in the previous layer be `attmx[0][1] == 0.09832697` (or `attmx[1][0] == 0.09632228`)? Are either of these values incidental and can be safely ignored?

Thanks in advance!
-Samuel

**Comment by jessevig** [comment]
Hi Samuel,
Thanks for your question, and apologies for the delayed response. Attention in BERT is actually asymmetric, due to the fact that the query and key vectors differ depending on the direction you compute the attention in. Hope that answers your question.
Jesse

**Comment by sronnqvist** [comment]
Thanks for your answer! Just for clarification: I assume that layer 11 is at the output, and understand the attention values that you are visualizing in the map view as those used to calculate the output representations. Am I correct? So, say, for the output representation of `[CLS]` at layer 11 and head 0, would the visualized links connecting to tokens to the left hand side/layer input correspond to the values in `att['a']['att'][11][0][0][:]`? 

Are the attention weights going in the opposite direction then irrelevant for interpreting the model, since you don't visualize both?

-Samuel
