### ISSUE TITLE
Vizualization for query-result pairs

### ISSUE THREAD

**Issue by iglimanaj** [jessevig/bertviz#50]
I am very impressed from the features **bertviz** is offering till now. I was wondering if there is any approach for vizualizing the relation between a query and the results ranked by a BERT Model fine tuned on the passage reranking task. This fine tuned model predicts the relevance of a passage being the right "response" to a query and it would be nice to somehow vizualize how the query is connected to the passages.

Thanks in advance!

**Comment by jessevig** [comment]
Apologies for the late response. This could be framed as a sentence-pair task in which the query might be represented as Sentence A in the BERT model, and the response would be represented as Sentence B. The combined input to the model would include both "sentences" and should work with the existing visualization. Or was there a different approach you were considering?
