### ISSUE TITLE
How to use bertviz with Transformers model

### ISSUE THREAD

**Issue by efatmae** [jessevig/bertviz#51]
Hi,
Can I use bertViz with Transformers model implemented using pytorch nn.Transform??

Thanks,
Fatma

**Comment by jessevig** [comment]
Hi,
I don't think it support this natively, but you can technically call BertViz with any such model where you have access to the attention weights. You would need to pass the data to head_view.py, model_view.py, or neuron_view.py in the expected format, e.g. as defined here: https://github.com/jessevig/bertviz/blob/590c957799c3c09a4e1306b43d9ec10785e53745/bertviz/head_view.py#L7

**Comment by thilakshiK** [comment]
@jessevig 
Hi, I have trained a transformer model using [fairseq](https://github.com/pytorch/fairseq/blob/master/fairseq/models/transformer.py).  Can I use bertviz?

Thanks

**Comment by jessevig** [comment]
In theory, there would be two ways to call BertViz using a fairseq model:

1. Extract the attention weights from the fairseq model and pass those directly to head_view.py in the specified format. However, my understanding is that fairseq has very limited support for returning attention weights, and doesn't do this for the encoder layers for example: https://github.com/pytorch/fairseq/issues/1484

2. Load a fairseq checkpoing into huggingface somehow. There is some discussion here: https://github.com/pytorch/fairseq/issues/1354. However, the example script they point to is a dead link. So I'm not sure how easy this is.

So unfortunately it seems that neither option is completely straightforward.
