### ISSUE TITLE
How to use bertviz for custom attention weights?

### ISSUE THREAD

**Issue by monk1337** [jessevig/bertviz#54]
Hi, I have one task specific model, where I am getting attention weights for each token. 

Example :

sentence     = [ 'Hello', 'world' ]
attention_w = [0.9, 0.1 ]

How I can use bertviz to visualize this output?

I tried to pass sentence and attention_w as 

head_view(attention_w , sentence )

But I am getting error : 

```
/mnt/bertviz_repo/bertviz/util.py in format_attention(attention)
      6         # 1 x num_heads x seq_len x seq_len
      7         if len(layer_attention.shape) != 4:
----> 8             raise ValueError("The attention tensor does not have the correct number of dimensions. Make sure you set "
      9                              "output_attentions=True when initializing your model.")
     10         squeezed.append(layer_attention.squeeze(0))

ValueError: The attention tensor does not have the correct number of dimensions. Make sure you set output_attentions=True when initializing your model.
```

**Comment by jessevig** [comment]
Hi,
You can visualize the attention weights from your own custom model but they need to be in the format specified below:

`def head_view(attention, tokens, sentence_b_start = None, prettify_tokens=True):
    """Render head view
        Args:
            attention: list of ``torch.FloatTensor``(one for each layer) of shape
                ``(batch_size(must be 1), num_heads, sequence_length, sequence_length)``
            tokens: list of tokens
            sentence_b_index: index of first wordpiece in sentence B if input text is sentence pair (optional)
            prettify_tokens: indicates whether to remove special characters in wordpieces, e.g. Ġ
    """`
So in this case it would need to be a list of length one (for a single layer) of pytorch tensors, each of which has shape [1, num_heads, sequence_length, sequence_length], which in your case might be [1, 1, 2, 2]. Does that answer your question?

**Comment by zhao1402072392** [comment]
Thank you for your sharing. May I ask why I made a mistake?Could you use this as an example of what input attention and token are? Thank you again !
sentence_a = ['cat','cat']
# sentence_b = ['dog','dog']
attn = torch.tensor([[[[0.1,0.9],[0.1,0.9]]]])
# print(attn.shape())
x = head_view(attn, sentence_a)

##############error########################
Traceback (most recent call last):
  File "D:/paper-transformerGNN/PIC/attention/head_view.py", line 94, in <module>
    x = head_view(attn, sentence_a)
  File "D:/paper-transformerGNN/PIC/attention/head_view.py", line 48, in head_view
    attn = format_attention(attention)
  File "D:\paper-transformerGNN\PIC\attention\util.py", line 8, in format_attention
    raise ValueError("The attention tensor does not have the correct number of dimensions. Make sure you set "
ValueError: The attention tensor does not have the correct number of dimensions. Make sure you set output_attentions=True when initializing your model.

**Comment by zhao1402072392** [comment]
Thank you for your sharing. May I ask why I made a mistake?Could you use this as an example of what input attention and token are? Thank you again !


sentence_a = ['cat','cat']
sentence_b = ['dog','dog']
attn = torch.tensor([[[[0.1,0.9],[0.1,0.9]]]])
x = head_view(attn, sentence_a)

##############error########################
Traceback (most recent call last):
File "D:/paper-transformerGNN/PIC/attention/head_view.py", line 94, in
x = head_view(attn, sentence_a)
File "D:/paper-transformerGNN/PIC/attention/head_view.py", line 48, in head_view
attn = format_attention(attention)
File "D:\paper-transformerGNN\PIC\attention\util.py", line 8, in format_attention
raise ValueError("The attention tensor does not have the correct number of dimensions. Make sure you set "
ValueError: The attention tensor does not have the correct number of dimensions. Make sure you set output_attentions=True when initializing your model.

**Comment by DrXZenG** [comment]
@zhao1402072392 

sentence_a = ['cat','cat']
sentence_b = ['dog','dog']
attn = torch.tensor([[[[0.1,0.9],[0.1,0.9]]]])

attn_new = []
for _ in range(len(sentence_a):
    attn_new.append(attn)

x = head_view(attn_new, sentence_a)

Hope this help.
