### ISSUE TITLE
bertviz_colab.ipynb broken ?

### ISSUE THREAD

**Issue by kartikperisetla** [jessevig/bertviz#55]
bertviz_colab.ipynb broken ?

![image](https://user-images.githubusercontent.com/2056777/93562427-e09c9900-f93a-11ea-956c-7817c1186b5f.png)

**Comment by jessevig** [comment]
Hi, are you using one of the Colab links from the repo itself? There may be some links to out-of-date Colabs on the web.

**Comment by haMeLd** [comment]
so how to fix this problem? if you can show me the way.

**Comment by jessevig** [comment]
Hi, if you visit the README here: https://github.com/jessevig/bertviz, you will see some links for "colab" for various views.
<img width="611" alt="Screen Shot 2020-10-03 at 3 27 13 PM" src="https://user-images.githubusercontent.com/45317205/95002816-170a2300-058d-11eb-9b99-9c756cdd88ab.png">

**Comment by kartikperisetla** [comment]
thank you!
