### ISSUE TITLE
Support for TensorFlow-based HuggingFace Models?

### ISSUE THREAD

**Issue by Diana960** [jessevig/bertviz#57]
I'm looking into using BertViz to visualize the attention weights on a BERT-based model that has been fine-tuned for a downstream task. We're starting from a TensorFlow-based version of the model from HuggingFace (we're more familiar with TF) and fine tuning with TensorFlow/Keras. I noticed in the requirements for BertViz that PyTorch is listed as a requirement, and all the samples seem to leverage PyTorch HuggingFace models. Just wondering if there's any particular issue with using a TF-based model with BertViz, or does it just mean we'd need to make some minor code changes on the part of BertViz's implementation to support TF models?

**Comment by jessevig** [comment]
Hi @Diana960  I just added a notebook that demonstrates visualizing a TF-based Huggingface model: https://github.com/jessevig/bertviz/blob/master/head_view_bert_tensorflow.ipynb 

For now, it still requires installing pytorch, as this notebook simply converts the TF model attention output to pytorch tensors. Please let me know if you have any questions or issues. Thanks.

**Comment by Diana960** [comment]
Thanks for the sample! After asking this question, I did find the easiest approach was just to convert Tensorflow tensors to PyTorch tensors prior to generating visualizations, as you suggested. Things seem to be working well for the head view and model view with this approach using the default models from HuggingFace, and I'm working on adapting them to our custom models. Will let you know if I have other questions.

**Comment by mv96** [comment]
@jessevig can you share the notebook again ?

**Comment by jessevig** [comment]
@mv96 This is the notebook I had previously shared: https://github.com/jessevig/bertviz/blob/04ba2d54c76a49a5f7ec3c98659470a4e830353b/notebooks/head_view_bert_tensorflow.ipynb

I'm not sure if it's the optimal way to do things.
