### ISSUE TITLE
no attribute 'bias' while loading a finetuned BERT from TF

### ISSUE THREAD

**Issue by gorka96** [jessevig/bertviz#58]
Hi!

I have a finetuned BERT model trained in Tensorflow and I would like to visualize its attentions.

I tried to load the model in different ways, but I always get the same error. Any suggestion at how to solve this no attribute bias error?
```
model = BertModel.from_pretrained(model_path, from_tf=True, output_attentions=True)
tokenizer = BertTokenizer.from_pretrained(model_version, do_lower_case=do_lower_case)

ModuleAttributeError: 'BertModel' object has no attribute 'bias'
```
```
model = BertForPreTraining.from_pretrained(model_path, from_tf=True, output_attentions=True)
tokenizer = BertTokenizer.from_pretrained(model_version, do_lower_case=do_lower_case)

ModuleAttributeError: 'BertForPreTraining' object has no attribute 'bias'
```
```
config = BertConfig.from_json_file(model_path+"config.json")
config.output_attentions = True
model = BertForPreTraining.from_pretrained(model_path+"model.ckpt.index", from_tf=True, config=config)

ModuleAttributeError: 'BertForPreTraining' object has no attribute 'bias'
```
```
model = AutoModelForPreTraining.from_pretrained(model_path, from_tf=True, output_attentions=True)
tokenizer = AutoTokenizer.from_pretrained(model_version, do_lower_case=do_lower_case)

ModuleAttributeError: 'AutoModelForPreTraining' object has no attribute 'bias'
```

Alternatively, I tried to convert my TF model to Pytorch using `transformers-cli convert`, and I was able to load the model and see the attentions. But they seem very fuzzy. Is this normal? Or did a make a mistake?

![Pantaila-argazkia 2020-10-29 15-40-01](https://user-images.githubusercontent.com/32821119/97589529-e7203500-19fd-11eb-9a5b-ef76ebde4e85.png)

Thanks

**Comment by jessevig** [comment]
Hi @gorka96 , I'm not sure about the conversion issues, but I just added a notebook that demonstrates how to use bertviz on a tensorflow model, described here: https://github.com/jessevig/bertviz/issues/57

Please let me know if that works for you, or if you have any questions or issues. Thanks.

**Comment by gorka96** [comment]
Thanks @jessevig for answer and your work. 

I'm starting from a tf checkpoint, for which transformers and TFBertForPretraining have no support, so I can't check if your solution for TF models works for me until I get to convert my tf1 checkpoint to TF2/Keras h5 model.
