### ISSUE TITLE
Head_view: wrong color rendering？

### ISSUE THREAD

**Issue by Albert-Ma** [jessevig/bertviz#61]
![image](https://user-images.githubusercontent.com/7343136/99747175-2f220b80-2b15-11eb-8adc-a5f54c0c4717.png)

The color of the line seems a little bit confused in the `head_veiw module`. In the tutorial or the blog post, it says that the color intensity reflects the attention weight. And for one token or word, it seems that it only uses one color to represent the attention weight. But in my example, it gives several colors for one token which makes me confused about which attention weight is bigger?

Thanks

**Comment by jessevig** [comment]
Hi @Albert-Ma, in this case you are seeing attention across all of the heads (represented by the colored squares at the top) .By single or double-clicking you can select/deselect the heads at the top to see the subset of attention weights associated with those heads. Let me know if that works for you.

**Comment by Albert-Ma** [comment]
@jessevig  Thanks, I'll try it.
