### ISSUE TITLE
GET nothing

### ISSUE THREAD

**Issue by liygzting** [jessevig/bertviz#63]
Hi
when I ran my model, it get noting
![gpt2](https://user-images.githubusercontent.com/73510109/102581444-8ed2fd00-413b-11eb-8066-12e27b822bcc.png)
Do I have to use colab?
Thanks

**Comment by jessevig** [comment]
Hi, you shouldn't have to use Colab. Would you be willing to share the content of the previous steps in the notebook to help me debug? Sometimes this can relate to how modules are imported. Thanks.

**Comment by liygzting** [comment]
Thank you for your reply
I can't connnect ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js
or any Google related website
the full code as follow
`import sys
!test -d bertviz_repo || git clone https://github.com/jessevig/bertviz bertviz_repo
if not 'bertviz_repo' in sys.path:
  sys.path += ['bertviz_repo']

import torch
from transformers import BertTokenizer, BertModel, GPT2LMHeadModel
from bertviz import head_view

def call_html():
  import IPython
  display(IPython.core.display.HTML('''
        <script src="/static/components/requirejs/require.js"></script>
        <script>
          requirejs.config({
            paths: {
              base: '/static/base',
              "d3": "https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.8/d3.min",
              jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min',
            },
          });
        </script>
        '''))
        
model_path = "./model_epoch11"
model = GPT2LMHeadModel.from_pretrained(model_path, output_attentions=True) 

vocab_file = "./dtc_vocab.txt"
with open(vocab_file,'r',encoding='utf-8') as f:
    vocab_ = f.readlines()

vocab_dict = dict()
for i, v in enumerate(vocab_):
    v = v.strip()
    vocab_dict[v] = i

line = "C19887 918F96 91C300 C16487 C21487 C19887 C43381 C43381 C19887 C19887 C19887 C11287 534104 C19887 918F96 91C300 C16487 C21487 C19887 C43381"
tokens = line.split()
ids = [vocab_dict[token] for token in tokens]
input_ids = torch.tensor(ids)
attention = model(input_ids)[-1]

call_html()
head_view(attention, tokens)`
![深度截图_选择区域_20201222090017](https://user-images.githubusercontent.com/73510109/102836464-6e08f100-4434-11eb-831e-9054e978fcc0.png)

**Comment by jessevig** [comment]
Are you running it in Jupyter Lab? I know one other person had this issue and resolved it by running it as a regular Jupyter Notebook: https://github.com/jessevig/bertviz/issues/53

If you do run it as a regular notebook, I would start with the notebook code included, eg. https://github.com/jessevig/bertviz/blob/master/head_view_bert.ipynb as opposed to the code found in the example colabs, as there are subtle differences between the two.

Sorry about the Jupyter Lab limitation, I will add a note to the README about that being a potential limitation. Let me know if you are able to run this in a regular Notebook or have other issues.

**Comment by javirandor** [comment]
I am experiencing this very same issue using Jupyter Notebook and this code.

```
import sys
!test -d bertviz_repo && echo "FYI: bertviz_repo directory already exists, to pull latest version uncomment this line: !rm -r bertviz_repo"
!rm -r bertviz_repo # Uncomment if you need a clean pull from repo
!test -d bertviz_repo || git clone https://github.com/jessevig/bertviz bertviz_repo
if not 'bertviz_repo' in sys.path:
    sys.path += ['bertviz_repo']
!pip install regex
!pip install transformers

from transformers import  DistilBertModel, DistilBertConfig, BertTokenizer
import torch
from bertviz import model_view, head_view

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tokenizer = BertTokenizer.from_pretrained("textattack/distilbert-base-uncased-imdb")
config = DistilBertConfig.from_pretrained('textattack/distilbert-base-uncased-imdb', output_hidden_states=True, output_attentions=True)
model = DistilBertModel.from_pretrained("textattack/distilbert-base-uncased-imdb", config=config)

%%javascript
require.config({
  paths: {
      d3: '//cdnjs.cloudflare.com/ajax/libs/d3/3.4.8/d3.min',
      jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min',
  }
});

def show_head_view(model, tokenizer, sentence_a, sentence_b=None):
    inputs = tokenizer.encode_plus(sentence_a, sentence_b, return_tensors='pt', add_special_tokens=True)
    input_ids = inputs['input_ids']
    if sentence_b:
        token_type_ids = inputs['token_type_ids']
        attention = model(input_ids, token_type_ids=token_type_ids)[-1]
        sentence_b_start = token_type_ids[0].tolist().index(1)
    else:
        attention = model(input_ids)[-1]
        sentence_b_start = None
    input_id_list = input_ids[0].tolist() # Batch index 0
    tokens = tokenizer.convert_ids_to_tokens(input_id_list)    
    head_view(attention, tokens, sentence_b_start)

show_head_view(model, tokenizer, "What a script, what a story, what a mess!")
```

**Comment by liygzting** [comment]
thanks @jessevig 
It's really like that
when I change to anaconda jupyter notebook 
my code work fine in local env

![截屏2020-12-22 21 56 02](https://user-images.githubusercontent.com/73510109/102895898-857dc380-44a0-11eb-8257-0a12512a6b77.png)

**Comment by jessevig** [comment]
@javirandor It might have to do with your imports. I am able to run your code successfully when I change the imports to those in the demo notebook:

```
import sys

from transformers import  DistilBertModel, DistilBertConfig, BertTokenizer
import torch
from bertviz import model_view, head_view

%%javascript
require.config({
  paths: {
      d3: '//cdnjs.cloudflare.com/ajax/libs/d3/3.4.8/d3.min',
      jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min',
  }
});

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tokenizer = BertTokenizer.from_pretrained("textattack/distilbert-base-uncased-imdb")
config = DistilBertConfig.from_pretrained('textattack/distilbert-base-uncased-imdb', output_hidden_states=True, output_attentions=True)
model = DistilBertModel.from_pretrained("textattack/distilbert-base-uncased-imdb", config=config)


def show_head_view(model, tokenizer, sentence_a, sentence_b=None):
    inputs = tokenizer.encode_plus(sentence_a, sentence_b, return_tensors='pt', add_special_tokens=True)
    input_ids = inputs['input_ids']
    if sentence_b:
        token_type_ids = inputs['token_type_ids']
        attention = model(input_ids, token_type_ids=token_type_ids)[-1]
        sentence_b_start = token_type_ids[0].tolist().index(1)
    else:
        attention = model(input_ids)[-1]
        sentence_b_start = None
    input_id_list = input_ids[0].tolist() # Batch index 0
    tokens = tokenizer.convert_ids_to_tokens(input_id_list)    
    head_view(attention, tokens, sentence_b_start)

show_head_view(model, tokenizer, "What a script, what a story, what a mess!")
```

![image](https://user-images.githubusercontent.com/45317205/103152413-89c60d00-473c-11eb-9c39-e24452c73fc3.png)

**Comment by blacksnail789521** [comment]
I think the problem is that bertviz will need to connect to other websites in order to do the rendering.
The solution to me is [export HTML file](https://github.com/jessevig/bertviz#obtain-html-representations) and open this file on some environment/machine that is able to connect to other websites.
