### ISSUE TITLE
How to use that tool to visualize the local fine-tuned Transformer model?

### ISSUE THREAD

**Issue by 14H034160212** [jessevig/bertviz#64]
Hi,

I have two questions. 
1. I have got the fine-tuned RoBERTa model, I want to visualize that fine-tuned model. How can I do that? From the tutorial, I do not see there is an example to visualize the local fine-tuned model.
2. Do I have to use the Huggingface model to get the Attention map, or Can I use the fairseq model to get the Attention map?
Thanks.

**Comment by jessevig** [comment]
Hi, you should be able to use it the same way with a fine-tuned Huggingface model. However, it may be more challenging with a fairseq model. See https://github.com/jessevig/bertviz/issues/51.
