### ISSUE TITLE
encoder-decoder attention?

### ISSUE THREAD

**Issue by xwuShirley** [jessevig/bertviz#67]
Dear Author,

Thank you very much for the visualization tool. It is super helpful.                                 
Now, we need to visualize the encoder-decoder attention instead of the self-attention. For instance, while using the following code, we only can visualize the self-attention one. It would be great if you can give some clue on how to visualize the encoder-decoder attention of BART. 

```
from bertviz import model_view
from bertviz import head_view
from transformers import BartForConditionalGeneration, BartTokenizer
model = BartForConditionalGeneration.from_pretrained("facebook/bart-large", force_bos_token_to_be_generated=True)
tokenizer = BartTokenizer.from_pretrained('facebook/bart-large')
sentence_a = "The cat sat on the mat"
sentence_b = "The cat lay on the rug"
inputs = tokenizer.encode_plus(sentence_a, sentence_b, return_tensors='pt', add_special_tokens=True)
input_ids = inputs['input_ids']
attention = model(input_ids,output_attentions=True)[2] ####
#print (attention.size())
input_id_list = input_ids[0].tolist() # Batch index 0
tokens = tokenizer.convert_ids_to_tokens(input_id_list)
model_view(attention, tokens)
head_view(attention, tokens)
```
Thank you!
Best,
Shirley

**Comment by jessevig** [comment]
Hi Shirley,
Thanks for reaching out. Unfortunately BertViz doesn't support encoder-decoder models out of the box. It seems that it should be possible to extract the cross-attention. After looking at the EncoderDecoderModel code, it's possible that the cross-attention is getting returned somewhere along the forward passs but not might be making it all the way back to the original forward call on the EncoderDecoderModel. I hope to look at it more at some point but unfortunately it might be a little while before I'll have the cycles to do that. If you are able to extract the cross attention, you should be able to still use the visualization tool with some hacking. There is precedent to visualizing attention with two input sentences, including the attention between them, here: https://github.com/jessevig/bertviz/blob/master/head_view_bert.ipynb . Of course this would need to be hacked to work for the case of encoder-decoder models. In the meantime, I'll at least update the README to be more clear about not supporting the encoder-decoder case.

**Comment by xwuShirley** [comment]
Thank you very much for the hint. I will work on it.

**Comment by jessevig** [comment]
Hi @xwuShirley, I've started a branch to visualize encoder-decoder attention: https://github.com/jessevig/bertviz/tree/encoder-decoder

I've added the `encoder_decoder.ipynb` notebook. 

```
git clone  -b encoder-decoder git@github.com:jessevig/bertviz.git
cd bertviz
jupyter notebook encoder_decoder.ipynb
```

Please let me know if that works for you. I'll work on adding support for the model view and pushing a new version to pypi as well soon.

![image](https://user-images.githubusercontent.com/45317205/116824527-97066480-ab3f-11eb-9221-bf1977247c8c.png)

**Comment by jessevig** [comment]
Encoder-decoder models now supported in Bertviz 1.1.0: https://github.com/jessevig/bertviz/blob/master/notebooks/head_view_encoder_decoder.ipynb

**Comment by chen-yifu** [comment]
Super helpful!! Thanks!
