### ISSUE TITLE
Visualizing Encoder Decoder Attention

### ISSUE THREAD

**Issue by kevin3567** [jessevig/bertviz#68]
I am wondering if there is a method visualize the attention between an encoder input and a decoder input (for seq2seq)? Current methods seems to only work for self attention.

**Comment by jessevig** [comment]
Hi, @kevin3567 thanks for your question. Unfortunately it doesn't work out-of-the-box for encoder-decoder models. I'll update the README to reflect that. It may be possible to get it to work with some hacking, as I mention here: https://github.com/jessevig/bertviz/issues/67 .
