### ISSUE TITLE
Question for use BertViz on my own model

### ISSUE THREAD

**Issue by leo88359** [jessevig/bertviz#69]
Hi, i have some problem of use BertViz on my own model, i'm not sure is that the correct way to change "model_version" like this

here is the code and error:
![pic](https://user-images.githubusercontent.com/81733870/113501766-532d3900-955a-11eb-9327-84abcffdce96.png)

![pic1](https://user-images.githubusercontent.com/81733870/113501774-693af980-955a-11eb-914a-f8b05af8d58d.png)

![pic2](https://user-images.githubusercontent.com/81733870/113501775-6d671700-955a-11eb-919a-3349cdb2eab2.png)

**Comment by jessevig** [comment]
Hi @leo88359, I'm not sure from looking at the error. Since this is happening prior to executing bertviz, you might have luck creating an issue on the Transformers repo (https://github.com/huggingface/transformers) .
Best,
Jesse

**Comment by leo88359** [comment]
Hi @jessevig , I had solve this problem, thank you so much! :)
