### ISSUE TITLE
Some words are unable to be visualized?

### ISSUE THREAD

**Issue by alvin-leong** [jessevig/bertviz#7]
It seems that some words not in the BERT vocab can be broken down into WordPiece tokens that are in the pretrained model and visualized, but others are not?

I tried this on some words from Norse mythology using the Colab notebook. "Ragnarok" can be broken down into rag ##nar ##ok but somehow "Valhalla" cannot. I tried it on sentences from tax documents and it doesn't quite work there either.

**Comment by alvin-leong** [comment]
Actually sorry, I don't think it has to do with tokenization. I managed to print the tokens for 'val', '##hall', '##a' successfully. And when I tried these two sentences:

sentence_a = "Google cheated the US government of taxes by moving to Ireland."
sentence_b = "It made use of something called transfer pricing to do so."

It also did not manage to create a visualization with show()

**Comment by jessevig** [comment]
Thank you for reporting this. I haven't been able to reproduce this behavior unfortunately. Can you tell me which of the Colab notebooks you are using? Also, could you try shortening the sentences and seeing if that makes a difference? You may need to pull the latest version of the Colab notebook to do this. Many thanks!
