### ISSUE TITLE
Neuron_view Asafaya pretrained model

### ISSUE THREAD

**Issue by hinnaweali** [jessevig/bertviz#77]
Hello,

We appreciate your assistance with this helpful visualization for Bert.
This issue occurs when I use the Asafaya pretrained model for the Arabic language, but not when I use the bert-base-multilingual-cased model.

![image](https://user-images.githubusercontent.com/30128513/127352083-80d2e0c4-218a-4f59-83e2-8b3b6649d3ee.png)

Any suggestions!

best,

**Comment by jessevig** [comment]
Hi @hinnaweali , this seems to work, though please check the output. Please let me know if it works for you.

Note that you would need to run it with the exact order of imports shown (there are two versions of BertModel that I'm using here).

`from transformers import BertModel, BertTokenizer
model = BertModel.from_pretrained('asafaya/bert-base-arabic', output_attentions=True)
model.save_pretrained('./model_neuron_view_test/')
from bertviz.transformers_neuron_view import BertModel
model = BertModel.from_pretrained('./model_neuron_view_test', output_attentions=True)
tokenizer = BertTokenizer.from_pretrained('asafaya/bert-base-arabic')
from bertviz.neuron_view import show
sentence_a = sentence_b = "هذا اختبار"
show(model, 'bert', tokenizer, sentence_a, sentence_b, display_mode='dark', layer=2, head=0)`

**Comment by hinnaweali** [comment]
Hello  Jesse,

I'd want to thank you for your helpful response.
Another issue arises, this time involving javascript visualization.
For example, using the show function with any head value yields no visual results. It is only possible to view a map with a layer value assigned. In addition,  Also, the visualization map's drop-down list only allows me to choose a layer/head of 0.

![image](https://user-images.githubusercontent.com/30128513/127746647-4bdb4b72-2f7f-42a0-9d59-5c8f323e0076.png)

best,
Ali

**Comment by jessevig** [comment]
Hmm, I see @hinnaweali . Could you paste in your code and I can try to run it just as you have it?

**Comment by hinnaweali** [comment]
It is the same code you sent. I only changed the sentences plus the layer and head values.


from transformers import BertModel, BertTokenizer
model = BertModel.from_pretrained('asafaya/bert-base-arabic', output_attentions=True)
model.save_pretrained('./model_neuron_view_test/')

from bertviz.bertviz.transformers_neuron_view import BertModel
model = BertModel.from_pretrained('./model_neuron_view_test', output_attentions=True)
tokenizer = BertTokenizer.from_pretrained('asafaya/bert-base-arabic')

from bertviz.bertviz.neuron_view import show
sentence_a = "طريقة إستعمال قطرة الانف للإطفال"
sentence_b = " اذا كانت قطر للتنظيف استعمل عند الحاجة قبل الرضعات و قبل النوم"
show(model, 'bert', tokenizer, sentence_a, sentence_b, display_mode='light', layer = 11, head = 6)

**Comment by jessevig** [comment]
Hi @hinnaweali this is what I get:

![image](https://user-images.githubusercontent.com/45317205/127747052-f5112bfd-e2aa-40bb-a117-6610f0e3fe3e.png)

What browser are you running on? Also, are you using vanilla jupyter notebook?

**Comment by hinnaweali** [comment]
It seems that I should use Jupyter Lab instead! I ran your code on both Microsoft Edge and Google Chrome.

**Comment by jessevig** [comment]
Hmm, I've been able to run it on regular Jupyter using Chrome. There might
be issues with Microsoft Edge though. Are you able to run the neuron view
in this standard notebook without changing anything?:
https://github.com/jessevig/bertviz/blob/master/notebooks/neuron_view_bert.ipynb

Also, which version of Transformers are you using? I'm using
transformers==4.9.1.
Curious if you can get your model to load in the head or model views
(should just be able to substitute your model name in the standard
notebook, e.g.:
https://github.com/jessevig/bertviz/blob/master/notebooks/head_view_bert.ipynb

**Comment by hinnaweali** [comment]
Hello Jesse,

Please accept my apologies for the delayed response.
The issue has been resolved by upgrading the transformer version of Jupyter notebbok from 4.4.2 to 4.9.1, using both Google Chrome and Microsoft Edge.

Regards,


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/hibaali/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/hibaali/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Visualization   Type | Browser | Transformer   version | Status | Kernel
-- | -- | -- | -- | --
neuron view | Edge | 4.9.1 | done successfuly | Jupyter Notebook
head view | Edge | 4.9.1 | done successfuly | Jupyter Notebook
Model   view | Edge | 4.9.1 | done successfuly | Jupyter Notebook
neuron view | Chrome | 4.9.1 | done successfuly | Jupyter Notebook
head view | Chrome | 4.9.1 | done successfuly | Jupyter Notebook
Model   view | Chrome | 4.9.1 | done successfuly | Jupyter Notebook



</body>

</html>

**Comment by jessevig** [comment]
Great! Thanks for the update.
