### ISSUE TITLE
support BART?

### ISSUE THREAD

**Issue by LiyingCheng95** [jessevig/bertviz#79]
Hi, I'm wondering if there's a visualization tool for BART. Thanks in advance!

**Comment by jessevig** [comment]
Hi, I haven't tried BART specifically but BertViz does support encoder-decoder models like BART: https://github.com/jessevig/bertviz#encoder-decoder-models-marianmt-etc

Please let me know if that works for you. Thanks!

**Comment by jessevig** [comment]
Hi, I've added some sample notebooks for BART, e.g. : https://github.com/jessevig/bertviz/blob/master/notebooks/model_view_bart.ipynb
