### ISSUE TITLE
standalone web demo

### ISSUE THREAD

**Issue by leemengtaiwan** [jessevig/bertviz#8]
Thanks for making such great visualization!

I wonder whether it is possible to render the vis for easier exploration into a normal html page rather than showing on jupyter notebook?

And suggestion or example for achieving this will be appreciated!

**Comment by jessevig** [comment]
Glad you found it useful, and thank you for your suggestion! I agree that would be nice to have a standalone web demo. Unfortunately I don't have an example to provide for this right now.
