### ISSUE TITLE
Support for BigBird

### ISSUE THREAD

**Issue by iamakshay1** [jessevig/bertviz#80]
Hi, When I am trying to run this for the BigBird model which is trained on Genomic Data, I am getting the following error: ValueError: Attention has 1024 positions, while the number of tokens is 976 for tokens 
![image](https://user-images.githubusercontent.com/63843448/134177136-0d16f880-d468-4223-acdb-912fe651b97d.png)

**Comment by jessevig** [comment]
Hi, I'm able to run a BigBird model in the trivial case:

```
from transformers import AutoTokenizer, AutoModel
from bertviz import model_view

model_name = 'google/bigbird-roberta-base'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name, output_attentions=True)
inputs = tokenizer.encode("The cat sat on the mat", return_tensors='pt')

outputs = model(inputs)
attention = outputs[-1]  # Output includes attention weights when output_attentions=True
tokens = tokenizer.convert_ids_to_tokens(inputs[0]) 
model_view(attention, tokens)
```

**Comment by jessevig** [comment]
Is this a publicly available model that you're working with? If so, would you mind sharing the name and associated code so that I can debug on my end? Thanks!
