### ISSUE TITLE
Attention visualization on a fine tuned model 'bert-base-cased'

### ISSUE THREAD

**Issue by realsazzad** [jessevig/bertviz#83]
Is there any example on how to use the bertviz on a fine tuned BERT model? I am getting the following error while using bertviz after loading fine tuned BERT model. 
TypeError: forward() missing 1 required positional argument: 'attention_mask'

**Comment by jessevig** [comment]
Hi @realsazzad, are you using the head view, the model view, or the neuron view?

**Comment by realsazzad** [comment]
Hello @jessevig, I have tried with model view.

**Comment by jessevig** [comment]
Okay, thanks. In that case, this seems like an error that is occurring when you call the model, prior to invoking BertViz? Can you share the code you are using? This may indicate that you are not passing the required 'attention_mask' parameter to your model. Typically the tokenizer.encode returns a dictionary that will include attention_mask, so it may also relate to how tokenization is being performed.

**Comment by realsazzad** [comment]
Hello @jessevig, thanks for the lead. The problem has been solved. The issue was :  not getting the right attention weights from the custom defined model.
