### ISSUE TITLE
Unserstanding BART notebook

### ISSUE THREAD

**Issue by ebagdasa** [jessevig/bertviz#84]
Hey

I am trying to use Bertviz to debug my BART model (specifically your notebook https://github.com/jessevig/bertviz/blob/master/notebooks/head_view_bart.ipynb ). I wonder if you have any advice on how to visualize the model's focus. Specifically, I am interested how the produced output words are impacted by specific input words.

Cross attention seems to mostly focus on \<s\> and '.' so I am not sure if I understand things correctly.
![Screen Shot 2021-11-16 at 08 43 58](https://user-images.githubusercontent.com/8597349/141996390-a3f6d892-cc09-4362-9f04-86df29979fde.png)

Thank you
Eugene

**Comment by jessevig** [comment]
Hi @ebagdasa ,
Sorry for the late reply. Attention isn't always neatly interpretable. One reason is that attention is applied to the contextualized representation / embedding at a particular token, not the original token embedding. This representation might mix in information from other parts of the sentence. For this and other reasons, attention isn't necessarily a direct _explanation_ of a model's behavior. If you are interested in _attributing_ a model's predictions to particular input tokens, I would recommend considering saliency methods, e.g. as discussed here: https://arxiv.org/abs/2010.05607. There are some libraries that may help, e.g. https://ai.googleblog.com/2020/11/the-language-interpretability-tool-lit.html and https://allennlp.org/interpret .
Best,
Jesse
