### ISSUE TITLE
Support for Electra models?

### ISSUE THREAD

**Issue by ltsc256** [jessevig/bertviz#85]
Would it be possible to extend bertviz to apply to electra models?

**Comment by jessevig** [comment]
Hi @ltsc256 the attention head view and the model view support Electra currently. Here's an example, please let me know if it doesn't work for you:

from transformers import ElectraTokenizer, ElectraModel

```
from bertviz import model_view

tokenizer = ElectraTokenizer.from_pretrained("google/electra-small-discriminator")
model = ElectraModel.from_pretrained("google/electra-small-discriminator", output_attentions=True)
inputs = tokenizer.encode("The cat sat on the mat", return_tensors='pt')
outputs = model(inputs)
attention = outputs[-1]  # Output includes attention weights when output_attentions=True
tokens = tokenizer.convert_ids_to_tokens(inputs[0]) 
model_view(attention, tokens)
```

**Comment by ltsc256** [comment]
oh excellent! I'll try again rn and update shortly. I was trying an electra for sequence classification and was getting an error but i'll try again now.

**Comment by ltsc256** [comment]
It works!
