### ISSUE TITLE
support for huggingface wav2vec XLSR ? 

### ISSUE THREAD

**Issue by StephennFernandes** [jessevig/bertviz#86]
Hey does bertviz support visualization for wav2vec XLSR ASR models from huggingface ?  where one end is a spectrogram and the other is corresponding transcriptions with attention visualizations of the corresponding text that the audio

**Comment by jessevig** [comment]
Hi @StephennFernandes, thanks for the question! Unfortunately bertviz only supports fully text-based models. Nice idea though.
Best,
Jesse

**Comment by StephennFernandes** [comment]
@jessevig do you know of any other alternatives that i can use to visualize the attention in wav2vec2 ASR models ? any leads you provide would really mean a lot

**Comment by jessevig** [comment]
Sorry @StephennFernandes I don't have any great suggestions there.
