### ISSUE TITLE
Error while using neuron_view

### ISSUE THREAD

**Issue by ashishgupta2598** [jessevig/bertviz#88]
Hii, The visualisation is fantastic but while using neuron view i am getting error. 
```show(model, 'bert', tokenizer, sentence_b, sentence_a, layer=2, head=0)```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_25767/3466440668.py in <module>
      1 sentence_a = "The cat sat on the mat"
      2 sentence_b = "The cat lay on the rug"
----> 3 show(model, 'bert', tokenizer, sentence_b, sentence_a, layer=2, head=0)

~/anaconda3/lib/python3.9/site-packages/bertviz/neuron_view.py in show(model, model_type, tokenizer, sentence_a, sentence_b, display_mode, layer, head)
     71     __location__ = os.path.realpath(
     72         os.path.join(os.getcwd(), os.path.dirname(__file__)))
---> 73     attn_data = get_attention(model, model_type, tokenizer, sentence_a, sentence_b, include_queries_and_keys=True)
     74     if model_type == 'gpt2':
     75         bidirectional = False

~/anaconda3/lib/python3.9/site-packages/bertviz/neuron_view.py in get_attention(model, model_type, tokenizer, sentence_a, sentence_b, include_queries_and_keys)
    174     for layer, attn_data in enumerate(attn_data_list):
    175         # Process attention
--> 176         attn = attn_data['attn'][0]  # assume batch_size=1; shape = [num_heads, source_seq_len, target_seq_len]
    177         attn_dict['all'].append(attn.tolist())
    178         if is_sentence_pair:

TypeError: new(): invalid data type 'str'
```
I have trained a mbert model(bert-base-uncased). Here its how I am loading the model
```
from transformers import AutoTokenizer, AutoModel, utils,BertModel,BertTokenizer
model = AutoModel.from_pretrained(model_name, output_attentions=True,from_tf=True)  # Configure model to return attention values
tokenizer = AutoTokenizer.from_pretrained(model_name)
```
All other views are working fantastic in my case. I have noticed from colab notebook that you are importing models from lib provided by your repo. Should I train my model too like that if you have modified it somewhere?

**Comment by jessevig** [comment]
Hi @ashishgupta2598, thanks for reaching out. Yes, unfortunately as mentioned [here](https://github.com/jessevig/bertviz#neuron-view-1), the neuron view is different than the other views in that it is limited to types of models that are compatible with the custom version of transformers (`transformers_neuron_view`) included with the repo. If you can produce a bert checkpoint that is compatible with this [bert implementation](https://github.com/jessevig/bertviz/blob/master/bertviz/transformers_neuron_view/modeling_bert.py) (which was forked from transformers ~2 years ago) you may be able to still use this. 

Also the neuron view is invoked differently compared to the other views:

```
from bertviz.transformers_neuron_view import BertModel, BertTokenizer
from bertviz.neuron_view import show

model_type = 'bert'
model_version = 'bert-base-uncased'
do_lower_case = True
sentence_a = "The cat sat on the mat"
sentence_b = "The cat lay on the rug"
model = BertModel.from_pretrained(model_version, output_attentions=True)
tokenizer = BertTokenizer.from_pretrained(model_version, do_lower_case=do_lower_case)
show(model, model_type, tokenizer, sentence_a, sentence_b, layer=2, head=0)
```

So you _may_ be able to get this to work with your model if you change `model_version` to the directory with your custom checkpoint.

**Comment by jessevig** [comment]
Let me know if you have any further questions about this.
