### ISSUE TITLE
Displaying results with Streamlit using JavaScript/HTML

### ISSUE THREAD

**Issue by chen-yifu** [jessevig/bertviz#90]
Hi,
Hope this message reaches you well. I am trying to deploy BertViz in a Streamlit app, which can display a visualization if an HTML/JavaScript string is provided. From the repo code, it seems that the raw HTML/JavaScript was not returned after the visualization was rendered. While I understand this is probably to improve out cleanliness in the Jupyter environment, I hope that `head_view` and `neuron_view` can optionally return the HTML/JavaScript code, so that I can embed the visualization in a web page. An example is available here https://share.streamlit.io/cdpierse/transformers-interpret-streamlit/main/app.py , you can view the source code by clicking the top-right menu. It allows to retrieve the visualization with `_repr_html_()`. 
Thank you!
Charles

**Comment by cyber-raskolnikov** [comment]
Hi,
I have implemented the feature that actually allows you to return the HTML visualizations.
You can use it by checking the fork I'm actually trying to pull request right now, it is also available at my forked repo.

Hope it'll be of help, further instructions on how to retrieve them are documented at the updated README.

**Comment by chen-yifu** [comment]
Thanks so much, this is super helpful and I will use it!

**Comment by jessevig** [comment]
Thanks to @cyber-raskolnikov this is now available in version 1.4.0. See https://github.com/jessevig/bertviz#obtain-html-representations
