### ISSUE TITLE
Showing nothing while no exception caught

### ISSUE THREAD

**Issue by Anbrose** [jessevig/bertviz#96]
Hi,

I'm trying to visualize the attention on my fine-tuned model, while the demo case works fine with us but when I try to feed attention results output by my fine-tuned model it's just showing blank but no exception was caught. I've been tried to slice the attention shape to the same as the one in demo case with [1,12,8,8] but still not working.

**Comment by Anbrose** [comment]
Hi,

Sorry about bothering you all. The problem was just solved. I think it's coming from a collision between imported packages. Will try to figure out which two caused that.

**Comment by jessevig** [comment]
Hi @Anbrose were you able to figure out what might have caused that?

**Comment by Anbrose** [comment]
> Hi @Anbrose were you able to figure out what might have caused that?

Hi @jessevig , sorry about the late update. I think this issue is not caused by the import stage. I've re-run the code might cause issues a couple of times, but it seems like none of these trails caused this issue again. 

Just in case someone else got the same problem in the future, I post my settings as following:

Macbook Pro (14 inch, 2021) using Monterey 12.2.1
Chip: M1 Pro
RAM: 16GB

**Comment by jessevig** [comment]
Thanks for getting back @Anbrose ! So is the issue currently resolved for you?

**Comment by Anbrose** [comment]
> Thanks for getting back @Anbrose ! So is the issue currently resolved for you?

@jessevig No worries. The answer is yes. Everything is running perfectly right now for me.

**Comment by jessevig** [comment]
Awesome, thank you! Please let me know if you run into any issues again! I'll close this for now.
