### ISSUE TITLE
show error

### ISSUE THREAD

**Issue by westwet** [jessevig/bertviz#99]
when I ran the demo, model_view didn't works for me.

![image](https://user-images.githubusercontent.com/50127348/167984901-d06e198a-74c4-4414-99ff-c54721d62fb8.png)

**Comment by westwet** [comment]
![image](https://user-images.githubusercontent.com/50127348/167984972-565d066b-b70f-4f00-a242-4f37b2ec7359.png)

**Comment by jessevig** [comment]
Hi @westwet, thanks for reporting that. Which version of BertViz are you using? If it's not the latest version (1.4.0), could you try `pip install bertviz==1.4.0` first? Many thanks.

**Comment by westwet** [comment]
@jessevig Thanks for your reply, I try to install bertviz == 1.4.0,but it still error
![image](https://user-images.githubusercontent.com/50127348/167989516-6abaa84f-3828-448e-b25c-c5d11c1aecd9.png)

**Comment by westwet** [comment]
> Hi @westwet, thanks for reporting that. Which version of BertViz are you using? If it's not the latest version (1.4.0), could you try `pip install bertviz==1.4.0` first? Many thanks.

still these errors
![image](https://user-images.githubusercontent.com/50127348/167989689-0d3b2090-34af-4c40-966b-5c3458edb1c5.png)
![image](https://user-images.githubusercontent.com/50127348/167989709-774ac8d5-1117-480b-b0fd-309ea7adca19.png)

**Comment by jessevig** [comment]
Okay, thanks for trying that out, sorry it didn't work. Can I ask: (1) What browser are you using? (Chrome, Firefox, etc.) and (2) How are you running the notebook? Is it vanilla jupyter notebook (e.g. from command line `jupyter notebook`?

**Comment by westwet** [comment]
> Okay, thanks for trying that out, sorry it didn't work. Can I ask: (1) What browser are you using? (Chrome, Firefox, etc.) and (2) How are you running the notebook? Is it vanilla jupyter notebook (e.g. from command line `jupyter notebook`?

Thanks for your asking.I use Microsoft Edge to run the notebook.
Yes I use jupyternotebook

**Comment by westwet** [comment]
I noticed that #93 has the same problem, but every method including `show`,`model_view` doesn't work for me

**Comment by jessevig** [comment]
Okay, thanks for getting back. Could you try running this step right before in the notebook (including all characters)?:

```
%%javascript
require.config({
  paths: {
      d3: '//cdnjs.cloudflare.com/ajax/libs/d3/5.7.0/d3.min',
      jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min',
  }
});
```

**Comment by jessevig** [comment]
> I noticed that #93 has the same problem, but every method including `show`,`model_view` doesn't work for me

Yes, they had the same issue though it seemed to resolve with latest BertViz version.

**Comment by westwet** [comment]
> Okay, thanks for getting back. Could you try running this step right before in the notebook (including all characters)?:
> 
> ```
> %%javascript
> require.config({
>   paths: {
>       d3: '//cdnjs.cloudflare.com/ajax/libs/d3/5.7.0/d3.min',
>       jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min',
>   }
> });
> ```

Okay, thanks for your replying, actually I tested this method, it didn't work for me
![image](https://user-images.githubusercontent.com/50127348/167991112-4fbaec80-12de-4333-a56f-d77f6ebcc68b.png)
![image](https://user-images.githubusercontent.com/50127348/167991130-5de3e58d-7c32-4d06-ae9d-d90d9d149b7d.png)

**Comment by jessevig** [comment]
Hmm, thanks for checking. Could you try one last thing if you would be so kind? This method below will save an HTML file with the visualization. You should be able to view it in your browser. Please just set the path to one that's appropriate for your system :

```
from transformers import AutoTokenizer, AutoModel, utils
from bertviz import head_view

utils.logging.set_verbosity_error()  # Suppress standard warnings
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased", output_attentions=True)

inputs = tokenizer.encode("The cat sat on the mat", return_tensors='pt')
outputs = model(inputs)
attention = outputs[-1]  # Output includes attention weights when output_attentions=True
tokens = tokenizer.convert_ids_to_tokens(inputs[0]) 

html_head_view = head_view(attention, tokens, html_action='return')

with open("PATH_TO_YOUR_FILE/head_view.html", 'w') as file:
    file.write(html_head_view.data)
```

**Comment by jessevig** [comment]
It may not be the ideal solution, but it will very much help with debugging :)

**Comment by westwet** [comment]
> Hmm, thanks for checking. Could you try one last thing if you would be so kind? This method below will save an HTML file with the visualization. You should be able to view it in your browser. Please just set the path to one that's appropriate for your system :
> 
> ```
> from transformers import AutoTokenizer, AutoModel, utils
> from bertviz import model_view
> 
> utils.logging.set_verbosity_error()  # Suppress standard warnings
> tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
> model = AutoModel.from_pretrained("bert-base-uncased", output_attentions=True)
> 
> inputs = tokenizer.encode("The cat sat on the mat", return_tensors='pt')
> outputs = model(inputs)
> attention = outputs[-1]  # Output includes attention weights when output_attentions=True
> tokens = tokenizer.convert_ids_to_tokens(inputs[0]) 
> 
> html_model_view = model_view(attention, tokens, html_action='return')
> 
> with open("PATH_TO_YOUR_FILE/model_view.html", 'w') as file:
>     file.write(html_model_view.data)
> ```

I am so sorry, I got nothing in my model_view.html. It is whole blank space
![image](https://user-images.githubusercontent.com/50127348/167992151-26e141b2-0ebd-4c3d-8ece-cda89865774b.png)
![image](https://user-images.githubusercontent.com/50127348/167992170-2c086405-21ea-4196-8996-c0164fe05b21.png)

**Comment by jessevig** [comment]
Hmm, thanks for trying that out. Can you render this page?: [https://jessevig.com/model_view.html ](https://jessevig.com/model_view.html )

**Comment by jessevig** [comment]
I ran the same code on my system and put the saved html at that link.

**Comment by westwet** [comment]
> Hmm, thanks for trying that out. Can you render this page?: [https://jessevig.com/model_view.html ](https://jessevig.com/model_view.html)

Amazing!! I can't render your page either

**Comment by jessevig** [comment]
Okay, this is very helpful, thank you! I was able to render it in an Edge emulator:

<img width="995" alt="image" src="https://user-images.githubusercontent.com/45317205/167993678-2e105851-cc82-4985-ab2a-500f47f6dfb3.png">

**Comment by jessevig** [comment]
I hate to suggest "clear the cache", but I wonder if this isn't playing nice with the current state of your browser for some reason. One option would be to try it in a different browser like Firefox if that's not too difficult.

**Comment by westwet** [comment]
> I hate to suggest "clear the cache", but I wonder if this isn't playing nice with the current state of your browser for some reason. One option would be to try it in a different browser like Firefox if that's not too difficult.

Thanks for your suggestion，I try to use Google to open jupyter notebook now

**Comment by westwet** [comment]
> I hate to suggest "clear the cache", but I wonder if this isn't playing nice with the current state of your browser for some reason. One option would be to try it in a different browser like Firefox if that's not too difficult.

emmm，I used Google to run my code, but still blank space

**Comment by jessevig** [comment]
Thanks. To clarify: what do you mean by "use Google"? Is this in a different browser, e.g. Chrome?

**Comment by westwet** [comment]
> > I hate to suggest "clear the cache", but I wonder if this isn't playing nice with the current state of your browser for some reason. One option would be to try it in a different browser like Firefox if that's not too difficult.
> 
> emmm，I used Google to run my code, but still blank space

I wonder if I am missing some dependency packages.

**Comment by westwet** [comment]
> Thanks. To clarify: what do you mean by "use Google"? Is this in a different browser, e.g. Chrome?

Yes, I opened my jupyter notebook using Google

**Comment by jessevig** [comment]
In this new browser, are you able to view https://jessevig.com/model_view.html ?

**Comment by westwet** [comment]
> In this new browser, are you able to view https://jessevig.com/model_view.html ?

No I am not, it is still a blank page.

**Comment by jessevig** [comment]
So both Microsoft Edge and Google Chrome give a blank page? Hmmm. Are you running on Windows?

**Comment by westwet** [comment]
> 

Yes , my OS is Windows

**Comment by westwet** [comment]
When I choose `head_view`, it is shown below.
![image](https://user-images.githubusercontent.com/50127348/167996548-f68d0823-ac4e-4af8-9c62-3da70a770e45.png)

**Comment by westwet** [comment]
> it is shown below

I also use FireFox to render your page, but it is still a blank page.

**Comment by jessevig** [comment]
Hmm. Can I ask what you get when you visit the following?:

https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js
https://cdnjs.cloudflare.com/ajax/libs/d3/5.7.0/d3.min.js

**Comment by westwet** [comment]
> 

These two web pages refused my access request.

**Comment by jessevig** [comment]
Okay! This is the root cause then. I'm not sure why this is happening, it may be an issue with your firewall. I googled `cloudflare refused access` and there seemed to be some relevant results. If you have the exact error, would you mind googling it along with `cloudflare` and see if it offers any good solutions?

**Comment by westwet** [comment]
> https://cdnjs.cloudflare.com/ajax/libs/d3/5.7.0/d3.min.js

Thank you very much. I'll find out how to solve this problem, and I'll let you know as soon as I get the relevant conclusion.

**Comment by jessevig** [comment]
Great, thank you!

**Comment by westwet** [comment]
> Great, thank you!

Sorry for late reply, the code worked for me when I changed my WIFI, thank you so much!! You are really kind man :)

**Comment by jessevig** [comment]
Good to know, thanks for getting back! One feature I'd like to add is better error handling so that these kinds of issues are easier to debug.

**Comment by westwet** [comment]
> Good to know, thanks for getting back! One feature I'd like to add is better error handling so that these kinds of issues are easier to debug.

Thank you so much, like the network problems I encountered, many people will encounter them. Error handing function is very helpful and valuable.
